site_name: Data Modeling
theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      primary: white
      accent: gray
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Public Sans"
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
        warning: material/alert-decagram-outline

repo_name: korawica/data-modeling
repo_url: https://github.com/korawica/data-modeling

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/korawica/data-modeling
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/korawica
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/korawica

nav:
  - Home:
    - index.md
    - Requirement Gathering: requirement-gathering.md
    - Transform Spec: transform-spec.md

  - Metadata:
    - Domains:
        - Customer: metadata/domains/customer.md
        - Address: metadata/domains/address.md
    - Structures:
        - Master: metadata/structures/master.md
        - Transaction: metadata/structures/transaction.md
        - ETL: metadata/structures/etl.md

  - Framework:
    - Node Strategy:
        - framework/node-strategy/index.md
        - Metadata: framework/node-strategy/metadata.md
    - Pipeline Strategy:
        - framework/pipeline-strategy/index.md
        - Metadata: framework/pipeline-strategy/metadata.md

plugins:
  - awesome-pages
  - tags
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  Copyright &copy; 2023 <a href="https://github.com/korawica/data-modeling" target="_blank" rel="noopener">Korawich Anuttra</a>
